# Generated by Django 5.1.3 on 2024-11-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testgroup",
            name="group_name",
            field=models.CharField(help_text="E.g. 'Rookies 2024' or 'ERD rules checkup'", max_length=255),
        ),
    ]
