# Generated by Django 5.1.3 on 2026-01-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pp", "0002_alter_testgroup_group_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
