# Generated by Django 5.1.3 on 2026-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pp", "0004_alter_question_question_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.ImageField(blank=True, null=True, upload_to="."),
        ),
    ]
