# Generated by Django 5.1.3 on 2026-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pp", "0006_alter_question_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testgroup",
            name="questions_amount",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                verbose_name=(
                    "How many questions would you like the test to have? (optional, will default to 40 if"
                    " left blank)"
                ),
            ),
        ),
    ]
